const mongoose = require('mongoose');


const urlSchema = new mongoose.Schema({
        shortId : {
            type : String,
            required : true,
            unique : true,
        },

        redirectURL : {
            type : String,
            required : true,
        },

        visitHistory : [{ timestamp : {type : Number}}],
        //now we need to see that urls that were generated by me onlyy
        createdBy :{
            type: mongoose.Schema.Types.ObjectId,
            ref:"users",
            //from this we get an id which reference the user
        },
        
},

{timestamps : true}

);

const URL = mongoose.models.url || mongoose.model("url",urlSchema);

module.exports = URL;